trigger: none
pr: none

parameters:
- name: ENVIRONMENT
  displayName: Environment
  type: string
  default: dev
  values:
    - dev
    - test
    - prod

variables:
- ${{ if eq(parameters.ENVIRONMENT, 'dev') }}:
  - name: tfstateconnection
    value: Terraform-State-Dev
  - name: tfresourceconnection
    value: Terraform-state-Dev
  - group: iac-solution_dev
  - group: tfstate_dev

- ${{ if eq(parameters.ENVIRONMENT, 'test') }}:
  - name: tfstateconnection
    value: Terraform-State-Test
  - name: tfresourceconnection
    value: Terraform-state-Test
  - group: iac-solution_test
  - group: tfstate_test

- ${{ if eq(parameters.ENVIRONMENT, 'prod') }}:
  - name: tfstateconnection
    value: Terraform-State-Prod
  - name: tfresourceconnection
    value: Terraform-state-Prod
  - group: iac-solution_prod
  - group: tfstate_prod

pool:
  vmImage: ubuntu-latest

jobs:
- deployment: TerraformDeploy
  environment: ${{ parameters.ENVIRONMENT }}
  displayName: Deployment of Terraform
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
            fetchDepth: 10
            sparseCheckoutDirectories: |
              .iac
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Terraform Initiatlization
            env:
              TF_INPUT: 'false'
              TF_VAR_AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(Build.SourcesDirectory)/.iac/'
              backendServiceArm: ${{ variables.tfstateconnection }}
              backendAzureRmStorageAccountName: $(TFSTATE_STORAGE-ACCOUNT_NAME)
              backendAzureRmContainerName: 'jeffbothel'
              backendAzureRmKey: 'CSU-CSC488-PortfolioProject/tfstate-${{ parameters.ENVIRONMENT }}.tfstate'
          - task: TerraformTask@5
            displayName: Terraform Validation
            env:
              TF_INPUT: 'false'
              TF_VAR_AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
            inputs:
              provider: azurerm
              command: validate
              workingDirectory: '$(Build.SourcesDirectory)/.iac/'
              environmentServiceNameAzureRM: ${{ variables.tfresourceconnection }}
          - task: TerraformTask@5
            displayName: Terraform Plan
            env:
              TF_INPUT: 'false'
              TF_VAR_AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
            inputs:
              provider: azurerm
              command: validate
              commandOptions: '--input=false -out=tfplan'
              workingDirectory: '$(Build.SourcesDirectory)/.iac/'
              environmentServiceNameAzureRM: ${{ variables.tfresourceconnection }}
          - task: TerraformTask@5
            displayName: Terraform Apply
            env:
              TF_INPUT: 'false'
              TF_VAR_AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
            inputs:
              provider: azurerm
              command: apply
              commandOptions: '--input=false tfplan'
              workingDirectory: '$(Build.SourcesDirectory)/.iac/'
              environmentServiceNameAzureRM: ${{ variables.tfresourceconnection }}